### PR TITLE
Fix twice element closing by htmlparser2

### LINKED ISSUE #33: Received a call to close "blockquote" but "div" was open
got an error when using > to input the blockquote,

### PR DESCRIPTION
**Pull request by yhatt**
`htmlparser2`'s `end()` will close the still opening elements in buffer. But it would close an element twice when only the opening renderer that is using HTML parser is overriden. It causes raising error by Incremental DOM.

We could fix by simply removing `htmlparser2.end()`.

Fix #33.

### CODE REVIEW

File: src/mixins/renderer.js [hunk 1]
```diff
@@ -1,15 +1,31 @@
...
-    elementVoid,
-    text,
-  } = incrementalDom
+  const autoClosingStack = []
+
+  const autoClosing = () => {
+    const stack = autoClosingStack.shift()
+    if (!stack) return
+
+    stack.reverse().forEach(tag => incrementalDom.elementClose(tag))
```
Comment (yhatt) [inline src/mixins/renderer.js]: This change means that the elements correction by htmlparser2 can no longer use. So we added the logic to close orphan elements caused by passing invalid HTML.
